/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'GetCurrentUser': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetUserProfile': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetSession': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UserLogout': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UserRegistration': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ResetPassword': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UserLogin': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ForgotPasswordRequest': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetVerificationToken': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'PrismaClientCheck': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
}